name: flutter_admin
description: 一个基于flutter的后台管理系统 - A management system based on flutter
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  cupertino_icons: ^1.0.5
  community_charts_flutter: ^1.0.0
  flutter_custom_clippers: ^2.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.0.0
  json_annotation: ^4.8.0
  bot_toast: ^4.0.0
  flutter_colorpicker: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  url_launcher: ^6.1.0
  universal_html: ^2.2.0
  mime_type: ^1.0.0
  image_picker: ^1.0.0
  image_picker_for_web: ^3.0.0
  video_player: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  build_runner: ^2.3.0
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
